---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-backend
  namespace: travel-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-backend
  template:
    metadata:
      labels:
        app: travel-backend
    spec:
      containers:
        - name: travel-backend
          image: ghcr.io/KLU2300031103/travel-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.travel-system.svc.cluster.local:3306/travelmanagement
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: SERVER_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: travel-backend
  namespace: travel-system
spec:
  selector:
    app: travel-backend
  ports:
    - port: 8081
      targetPort: 8081
      name: http
