apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-frontend
  namespace: travel-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-frontend
  template:
    metadata:
      labels:
        app: travel-frontend
    spec:
      containers:
        - name: travel-frontend
          image: ghcr.io/KLU2300031103/travel-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: travel-frontend
  namespace: travel-system
spec:
  selector:
    app: travel-frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
